## Part : 1 

## Ans : 1 

In TensorFlow, the primary data structure used for representing data is a tensor. A tensor is a multi-dimensional array, similar to NumPy arrays, but with additional capabilities optimized for deep learning tasks. Here are the main data structures used in TensorFlow:

### 1. **Tensor:**
   - A tensor is a multi-dimensional array of numerical values with a specific data type, such as float32, int32, etc. Tensors can have different ranks, representing different dimensions.
   - **Examples:**
     - Scalar (Rank 0 Tensor): A single number.
     - Vector (Rank 1 Tensor): One-dimensional array of numbers.
     - Matrix (Rank 2 Tensor): Two-dimensional array of numbers.
     - Higher-dimensional tensors: Tensors with more than two dimensions.

### 2. **Variable:**
   - A variable is a special type of tensor that is used to store mutable state, such as the weights and biases in a neural network. Variables are typically used for trainable parameters.
   - **Example:**
     ```python
     import tensorflow as tf
     variable = tf.Variable(initial_value=[1, 2, 3], dtype=tf.float32)
     ```

### 3. **Placeholder (Deprecated in TensorFlow 2.x):**
   - Placeholders were used in TensorFlow 1.x for feeding data into a computational graph. However, in TensorFlow 2.x, eager execution is the default mode, and placeholders are not required.
   - **Example (TensorFlow 1.x, not recommended in TensorFlow 2.x):**
     ```python
     import tensorflow as tf
     x = tf.placeholder(tf.float32, shape=(None, 784))  # Placeholder for input data
     ```

### 4. **SparseTensor:**
   - Sparse tensors are a special type of tensor used to efficiently represent sparse data, where most of the elements are zero.
   - **Example:**
     ```python
     import tensorflow as tf
     indices = tf.constant([[0, 1], [1, 2]])
     values = tf.constant([4, 5], dtype=tf.int32)
     sparse_tensor = tf.sparse.SparseTensor(indices=indices, values=values, dense_shape=[3, 4])
     ```

### 5. **RaggedTensor:**
   - A ragged tensor is used to represent nested variable-length lists of tensors. Ragged tensors are useful when dealing with sequences of varying lengths.
   - **Example:**
     ```python
     import tensorflow as tf
     ragged_tensor = tf.ragged.constant([[1, 2], [3, 4, 5], [6]])
     ```

### 6. **StringTensor:**
   - A string tensor is used to store and manipulate strings. It is often used for handling text data.
   - **Example:**
     ```python
     import tensorflow as tf
     string_tensor = tf.constant(["apple", "banana", "cherry"])
     ```

These are some of the main data structures used in TensorFlow. Tensors are the fundamental building blocks for creating computational graphs and performing various operations in TensorFlow. Depending on the type of data and the task at hand, you can choose the appropriate data structure to represent and process your data efficiently.

## Ans : 2

In TensorFlow, constants and variables are two different types of tensors used to hold data within a computational graph. Here's how they differ:

### TensorFlow Constant:

1. **Immutability:** Constants are immutable, meaning their value cannot be changed once they are defined. Once set, a constant's value remains the same throughout the execution of the graph.

2. **Usage:** Constants are used for values that do not change, such as hyperparameters, configuration values, or fixed data.

3. **Defined Value:** Constants have a fixed, known value at the time of graph construction.

#### Example of TensorFlow Constant:
```python
import tensorflow as tf

# Creating a TensorFlow constant
constant_value = tf.constant([1, 2, 3, 4])

# Attempting to change the value of a constant will result in an error
# constant_value.assign([5, 6, 7, 8])  # This line would raise an error
```

### TensorFlow Variable:

1. **Mutability:** Variables are mutable, meaning their value can be changed during the execution of the graph. Variables are typically used to store model parameters like weights and biases that need to be updated and optimized during training.

2. **Usage:** Variables are used for values that need to be learned and adjusted by the optimization algorithm (e.g., weights in a neural network).

3. **Initialization:** Variables need to be explicitly initialized before they can be used. You can set an initial value for a variable, and during training, their values are updated by optimizers like gradient descent.

#### Example of TensorFlow Variable:
```python
import tensorflow as tf

# Creating a TensorFlow variable with an initial value
initial_value = tf.constant([1, 2, 3, 4], dtype=tf.float32)
variable = tf.Variable(initial_value)

# Changing the value of a variable using assign
new_value = tf.constant([5, 6, 7, 8], dtype=tf.float32)
variable.assign(new_value)

# During training, variables are updated by optimizers based on the loss and gradients
# For example, in a neural network, variables (weights) are updated during backpropagation
```

In summary, constants are used for fixed, unchangeable values in the graph, while variables are mutable and can be modified during the execution of the graph. Variables are typically employed to store and update the model's parameters, allowing the model to learn from the data during training.

## Ans : 3 

In TensorFlow, matrix addition, multiplication, and element-wise operations can be performed using various functions and operators. Here's a description of each process:

### Matrix Addition:

Matrix addition is the process of adding two matrices of the same dimensions element-wise. In TensorFlow, you can perform matrix addition using the `tf.add()` function or the `+` operator. Both methods add corresponding elements of the matrices.

#### Example of Matrix Addition:
```python
import tensorflow as tf

# Define two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Perform matrix addition
result = tf.add(matrix1, matrix2)

# Alternatively, you can use the + operator
result_alternative = matrix1 + matrix2

print(result.numpy())  # Output: [[6  8] [10 12]]
print(result_alternative.numpy())  # Output: [[6  8] [10 12]]
```

### Matrix Multiplication:

Matrix multiplication is the process of multiplying two matrices following a specific rule. In TensorFlow, you can perform matrix multiplication using the `tf.matmul()` function or the `@` operator.

#### Example of Matrix Multiplication:
```python
import tensorflow as tf

# Define two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
result = tf.matmul(matrix1, matrix2)

# Alternatively, you can use the @ operator
result_alternative = matrix1 @ matrix2

print(result.numpy())  # Output: [[19 22] [43 50]]
print(result_alternative.numpy())  # Output: [[19 22] [43 50]]
```

### Element-wise Operations:

Element-wise operations are operations where corresponding elements of two matrices (or tensors) are operated independently. Common element-wise operations include addition, subtraction, multiplication, division, and more.

In TensorFlow, you can perform element-wise operations using standard arithmetic operators (`+`, `-`, `*`, `/`) or specific functions like `tf.add()`, `tf.subtract()`, `tf.multiply()`, and `tf.divide()`.

#### Example of Element-wise Operations:
```python
import tensorflow as tf

# Define two matrices
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

# Perform element-wise operations
addition_result = tf.add(matrix1, matrix2)  # Element-wise addition
subtraction_result = tf.subtract(matrix1, matrix2)  # Element-wise subtraction
multiplication_result = tf.multiply(matrix1, matrix2)  # Element-wise multiplication
division_result = tf.divide(matrix1, matrix2)  # Element-wise division

print(addition_result.numpy())  # Output: [[6  8] [10 12]]
print(subtraction_result.numpy())  # Output: [[-4 -4] [-4 -4]]
print(multiplication_result.numpy())  # Output: [[5 12] [21 32]]
print(division_result.numpy())  # Output: [[0.2        0.33333333] [0.42857143 0.5       ]]
```

In all these operations, TensorFlow performs the operations element-wise, considering the corresponding elements of the input matrices or tensors. The choice of operation depends on the specific use case and the mathematical requirements of the problem at hand.

## Part : 2 

## Task : 1 

### Ans :  1

In [50]:
import tensorflow as tf 

A = tf.random.normal(shape = (3,3), mean = 0 , stddev = 1 , dtype = tf.float32)
print(A.numpy())

[[-0.54176927 -0.3807034  -1.8638769 ]
 [-0.89440566 -0.65095127 -0.25995365]
 [-0.14153121 -0.38633245 -1.0061451 ]]


### Ans : 2

In [52]:
B = tf.random.truncated_normal(shape = (4,4) , mean = 0 , stddev = 1,dtype = tf.float32)
print(B.numpy())

[[ 1.6622524  -1.2435993  -1.3519237  -1.0861355 ]
 [ 0.911419   -0.22423138 -1.1155499   1.4422889 ]
 [ 0.59034944 -1.1675031   0.4334078   0.23111399]
 [-1.4110754  -0.41610408  0.22081456  0.29646415]]


### Ans : 3

In [53]:
C = tf.random.normal(shape = (2,2), mean = 3 , stddev = 0.5)
print(C.numpy())

[[2.7982044 3.8651507]
 [4.139677  3.2514818]]


### Ans : 4

In [64]:
import tensorflow as tf

# Define tensors A and B
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

# Perform tensor addition
D = tf.add(A, B)

# Display the result tensor D
print("Matrix A:")
print(A.numpy())
print("Matrix B:")
print(B.numpy())
print("Matrix D (Result of A + B):")
print(D.numpy())


Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Matrix D (Result of A + B):
[[ 6  8]
 [10 12]]


### Ans : 5

In [68]:
E = tf.multiply(tf.cast(C,dtype=tf.int32),tf.cast(D,dtype=tf.int32))
print(E.numpy())

[[12 24]
 [40 36]]


## Task : 2

### Ans : 1

In [81]:
F = tf.random.uniform(shape = (3,3))
print(F.numpy())

[[0.35920727 0.3981316  0.1860156 ]
 [0.41570544 0.31219304 0.71973825]
 [0.5197617  0.854494   0.47276485]]


### Ans : 2

In [82]:
G = tf.transpose(F,conjugate=True)
print(G.numpy())

[[0.35920727 0.41570544 0.5197617 ]
 [0.3981316  0.31219304 0.854494  ]
 [0.1860156  0.71973825 0.47276485]]


### Ans : 3

In [84]:
H = tf.exp(F)
print(H.numpy())

[[1.4321936 1.48904   1.2044411]
 [1.5154394 1.3664185 2.0538955]
 [1.6816268 2.350185  1.604424 ]]


### Ans : 4

In [86]:
I = tf.concat([F,G],axis = 1)
print(I.numpy())

[[0.35920727 0.3981316  0.1860156  0.35920727 0.41570544 0.5197617 ]
 [0.41570544 0.31219304 0.71973825 0.3981316  0.31219304 0.854494  ]
 [0.5197617  0.854494   0.47276485 0.1860156  0.71973825 0.47276485]]


### Ans : 5

In [88]:
J = tf.concat([F,H],axis = 0)
print(J.numpy())

[[0.35920727 0.3981316  0.1860156 ]
 [0.41570544 0.31219304 0.71973825]
 [0.5197617  0.854494   0.47276485]
 [1.4321936  1.48904    1.2044411 ]
 [1.5154394  1.3664185  2.0538955 ]
 [1.6816268  2.350185   1.604424  ]]
